apiVersion: v1
data:
  config.yaml: |
    #---------------------------------------------------#
    ## 更新：2023-08-18 08:16:29
    ## 感谢：https://github.com/Hackl0us/SS-Rule-Snippet
    ## 链接：https://doata.net/link/gg9v6HHtVi2LdRC1?clash=1
    #---------------------------------------------------#
    please input you config.yaml
kind: ConfigMap
metadata:
  name: clash-config
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clash
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clash
  template:
    metadata:
      labels:
        app: clash
    spec:
      initContainers:
        - image: sky94520/country-mmdb:1
          name: cpmmdb
          command: ["cp", "-r", "/web/Country.mmdb", "/app"]
          volumeMounts:
            - mountPath: /app
              name: mmdb-volume
      containers:
        - name: clash
          image: dreamacro/clash:v1.18.0
          command: ["/clash", "-d", "/data", "-f", "/data/config/config.yaml"]
          ports:
            - containerPort: 7890
            - containerPort: 9090
          volumeMounts:
            - mountPath: /data
              name: mmdb-volume
            - mountPath: /data/config
              name: config
      volumes:
        - name: mmdb-volume
          emptyDir: {}
        - name: config
          configMap:
            name: clash-config
            items:
              - key: config.yaml
                path: config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: clash-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 7890
      targetPort: 7890
      protocol: TCP
      name: tcp
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: restful
  selector:
    app: clash